[project]
name = "baba-stock-analysis"
version = "1.0.0"
description = "BABA stock data analysis from 2020-2021"
dependencies = [
    "matplotlib>=3.10.8",
    "pandas>=2.3.3",
    "yfinance>=1.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
